name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [ "main", "develop" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ommia-backend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      image_tag: ${{ steps.generate_tag.outputs.image_tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Image Tag
        id: generate_tag
        run: |
          SHORT_SHA="${GITHUB_SHA:0:7}"
          TIMESTAMP=$(TZ="Asia/Seoul" date +'%Y%m%d%H%M%S')
          IMAGE_TAG="${SHORT_SHA}-${TIMESTAMP}"
          
          echo "생성된 이미지 태그: ${IMAGE_TAG}"
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        run: |
          # 이미지명 소문자로 정의
          BASE_IMAGE_NAME=$(echo "${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
              
          IMAGE_TAG="${{ steps.generate_tag.outputs.image_tag }}"
          FULL_IMAGE_TAG="${BASE_IMAGE_NAME}:${IMAGE_TAG}"
        
          # 이미지 빌드 후 push
          docker build -t $FULL_IMAGE_TAG .           
          docker push $FULL_IMAGE_TAG 

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read

    steps:
      - name: Deploy to Private Server
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.PRIVATE_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          proxy_host: ${{ secrets.BASTION_PUBLIC_IP }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_key: ${{ secrets.KEY }}
          proxy_port: ${{ secrets.PORT }}
          script: |
            BASE_IMAGE_NAME=$(echo "${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
            
            IMAGE_TAG="${{ needs.build.outputs.image_tag }}"
            FULL_IMAGE_NAME="${BASE_IMAGE_NAME}:${IMAGE_TAG}"
            
            echo "${{ secrets.GHCR_PAT }}" | 
              docker login ghcr.io \
                -u ${{ github.actor }} \
                --password-stdin
             
            docker pull $FULL_IMAGE_NAME
              
            docker rm -f ommia-backend || true
            
            docker run -d \
              --name ommia-backend \
              --env-file /home/${{ secrets.USERNAME }}/.env \
              -p 8080:8080 \
              --restart always \
              $FULL_IMAGE_NAME